# Generated by Django 4.2.6 on 2024-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature_product/media/images/')),
                ('name', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('quentity', models.CharField(max_length=20, null=True)),
                ('product_code', models.CharField(max_length=20, null=True)),
                ('Shopping_text', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True)),
            ],
        ),
    ]
