# Generated by Django 4.2.6 on 2024-02-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyProduct',
            new_name='Featuere_product',
        ),
    ]
