# Generated by Django 4.2.6 on 2024-02-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Daily_product/media/images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
