# Generated by Django 4.2.6 on 2024-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daily_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduct',
            name='Shopping_tex',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduct',
            name='product_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduct',
            name='quentity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduct',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproduct',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dailyproduct',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
