# Generated by Django 4.2.6 on 2024-02-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttag'),
        ),
    ]
