# Generated by Django 4.2.6 on 2024-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_product_tag_product_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
