# Generated by Django 4.2.6 on 2024-03-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderproduct_city_orderproduct_credit_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='current_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
